version: "3.8"
services:
  flask-app:
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  mysql-petclinic:
    image: mysql:5.7.8
    restart: always
    environment:
      MYSQL_DATABASE: 'mysql-petclinic'
      MYSQL_USER: 'pc'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'petclinic'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-petclinic-db:/var/lib/mysql
# Names our volume
volumes:
  mysql-petclinic-db: