version: '3.7'
services:
  frontend:
    container_name: spring-petclinic-angular
    build: ./spring-petclinic-angular
    image: 16.3-alpine-spring-petclinic-angular:latest
    ports:
    - target: 8080
      published: 8080
  backend:
    container_name: spring-petclinic-rest
    build: ./spring-petclinic-rest
    image: openjdk-spring-petclinic-rest:latest
    ports:
    - target: 9966
      published: 9966 
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
      