pipeline{
        agent any
        environment {
            app_version = 'v1'
            rollback = 'false'
        }
        stages{
            stage('Build Image'){
                steps{
                    dir('chaperootodo_client') {
                    script{
                        if (env.rollback == 'false'){
                            image = docker.build("nero2013/chaperoo-frontend")
                        }
                    }
                    }
                }
            }
            stage('Tag & Push Image'){
                steps{
                    script{
                        if (env.rollback == 'false'){
                            docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials'){
                                image.push("${env.app_version}")
                            }
                        }
                    }
                }
            }
            stage('Deploy App'){
                steps{
                    withCredentials([string(credentialsId: 'DATABASE_PASSWORD', variable: 'DB_PASSWORD')]) {
                    sh '''docker-compose pull
                    docker-compose up -d'''
                    }
                  //  sh "docker-compose pull && docker-compose up -d"
                }
            }
        }
}
