pipeline{
        agent any
        stages{
            stage('Clone a git repo'){
                steps{
                     git branch: 'main', url: 'https://gitlab.com/qacdevops/chaperootodo_client.git'
                }
            }
            stage('Install docker & docker compose'){
                steps{
                    sh '''sudo apt-get update
                          sudo apt install curl jq -y
                          curl https://get.docker.com | sudo bash
                          sudo usermod -aG docker $(whoami)
                          sudo curl -L "https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-"$(uname -s)"-"$(uname -m)"" -o /usr/local/bin/docker-compose
                          sudo chmod +x /usr/local/bin/docker-compose'''
                }
            }
            stage('Deploy Application'){
                environment{
                    DB_PASSWORD = credentials('DATABASE_PASSWORD')
                }
                 steps {
                withCredentials([string(credentialsId: 'DATABASE_PASSWORD', variable: 'DB_PASSWORD')]) {
                    sh '''docker-compose pull
                    docker-compose up -d'''
                }
            }
        }
   }
}